[wokwi]
version = 1
firmware = 'target/riscv32imc-esp-espidf/debug/wokwi-crash'
elf = 'target/riscv32imc-esp-espidf/debug/wokwi-crash'

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"